# Assignment -3 

# Importing Iris Dataset

In [1]:
from sklearn import datasets
iris = datasets.load_iris()

In [3]:
iris


{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

# Data Preprocessing

In [85]:
X = iris.data
y1 = iris.target.reshape(-1,1)

In [86]:
x_min, x_max = X[:, 0].min() - 0.5, X[:, 0].max() + 0.5
y_min, y_max = X[:, 1].min() - 0.5, X[:, 1].max() + 0.5
print(X,y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [87]:
x_min,y_min

(3.8, 1.5)

In [88]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
plt.figure(2, figsize=(8, 6))
plt.clf()

<Figure size 576x432 with 0 Axes>

In [89]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y1)
y

C:\Users\91700\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:395: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  check_array(X, dtype=np.int)
C:\Users\91700\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

# Train_Test_Split

In [92]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.20)

In [93]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120, 3)


# sequential model with activation function as relu

In [94]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import adam_v2 as adam
model = Sequential()
model.add(Dense(10,input_dim=4,activation='relu',name='fc1'))
model.add(Dense(10,activation='relu',name='fc2'))
model.add(Dense(3,activation='softmax',name='output'))
model.compile(optimizer='adam',loss='categorical_crossentropy')

In [95]:
model.summary()

Model: "sequential_28"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 fc1 (Dense)                 (None, 10)                50        
                                                                 
 fc2 (Dense)                 (None, 10)                110       
                                                                 
 output (Dense)              (None, 3)                 33        
                                                                 
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________


# Model fitting

In [99]:
model.fit(X_train,y_train,batch_size=5,verbose=2,epochs=200)

Epoch 1/200
24/24 - 0s - loss: 1.0220 - 149ms/epoch - 6ms/step
Epoch 2/200
24/24 - 0s - loss: 1.0044 - 28ms/epoch - 1ms/step
Epoch 3/200
24/24 - 0s - loss: 0.9817 - 27ms/epoch - 1ms/step
Epoch 4/200
24/24 - 0s - loss: 0.9583 - 25ms/epoch - 1ms/step
Epoch 5/200
24/24 - 0s - loss: 0.9340 - 28ms/epoch - 1ms/step
Epoch 6/200
24/24 - 0s - loss: 0.9072 - 29ms/epoch - 1ms/step
Epoch 7/200
24/24 - 0s - loss: 0.8796 - 27ms/epoch - 1ms/step
Epoch 8/200
24/24 - 0s - loss: 0.8519 - 29ms/epoch - 1ms/step
Epoch 9/200
24/24 - 0s - loss: 0.8273 - 27ms/epoch - 1ms/step
Epoch 10/200
24/24 - 0s - loss: 0.8035 - 28ms/epoch - 1ms/step
Epoch 11/200
24/24 - 0s - loss: 0.7829 - 27ms/epoch - 1ms/step
Epoch 12/200
24/24 - 0s - loss: 0.7651 - 29ms/epoch - 1ms/step
Epoch 13/200
24/24 - 0s - loss: 0.7487 - 26ms/epoch - 1ms/step
Epoch 14/200
24/24 - 0s - loss: 0.7342 - 27ms/epoch - 1ms/step
Epoch 15/200
24/24 - 0s - loss: 0.7216 - 28ms/epoch - 1ms/step
Epoch 16/200
24/24 - 0s - loss: 0.7093 - 28ms/epoch - 1ms/step


Epoch 131/200
24/24 - 0s - loss: 0.1008 - 26ms/epoch - 1ms/step
Epoch 132/200
24/24 - 0s - loss: 0.1047 - 27ms/epoch - 1ms/step
Epoch 133/200
24/24 - 0s - loss: 0.1100 - 25ms/epoch - 1ms/step
Epoch 134/200
24/24 - 0s - loss: 0.0994 - 26ms/epoch - 1ms/step
Epoch 135/200
24/24 - 0s - loss: 0.0954 - 25ms/epoch - 1ms/step
Epoch 136/200
24/24 - 0s - loss: 0.1113 - 25ms/epoch - 1ms/step
Epoch 137/200
24/24 - 0s - loss: 0.1069 - 25ms/epoch - 1ms/step
Epoch 138/200
24/24 - 0s - loss: 0.0991 - 25ms/epoch - 1ms/step
Epoch 139/200
24/24 - 0s - loss: 0.1040 - 27ms/epoch - 1ms/step
Epoch 140/200
24/24 - 0s - loss: 0.1032 - 25ms/epoch - 1ms/step
Epoch 141/200
24/24 - 0s - loss: 0.0946 - 26ms/epoch - 1ms/step
Epoch 142/200
24/24 - 0s - loss: 0.0999 - 26ms/epoch - 1ms/step
Epoch 143/200
24/24 - 0s - loss: 0.1150 - 25ms/epoch - 1ms/step
Epoch 144/200
24/24 - 0s - loss: 0.1055 - 26ms/epoch - 1ms/step
Epoch 145/200
24/24 - 0s - loss: 0.1062 - 26ms/epoch - 1ms/step
Epoch 146/200
24/24 - 0s - loss: 0.0939 

# Testing Model 

In [100]:
result = model.evaluate(X_test,y_test)

1/1 [==============================] - 0s 105ms/step - loss: 0.0127


In [105]:
result

0.012664137408137321

In [106]:
print("Accuracy:",(1 - result)*100)

Accuracy: 98.73358625918627
